### ISSUE TITLE
Transfers and EconomicEvents not saved when logging Exchange

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#222]
https://testocp.freedomcoop.eu/work/agent/96/exchange-logging-work/0/128/

I attempted to save both transfers by clicking the New Transfer buttons. Neither of them were saved, and I did not get any error messages.

Tried twice, same (lack of) results.

**Comment by bhaugen** [comment]
Tried again, creating a new exchange of the same type. Same problem.

**Comment by bhaugen** [comment]
Rechecking: on https://testocp.freedomcoop.eu/work/agent/96/exchange-logging-work/0/130/
two commitments appeared that had not appeared on my last test (previous comment). (Apparently from Telegram @bum2 created them.)

I had in fact intended to create two actual transfers, not commitments. I am pretty sure I had selected New Transfer, not New Commitment. Will try again on https://testocp.freedomcoop.eu/work/agent/96/exchange-logging-work/0/128/

Same thing happened. I definitely clicked New Transfer. The hover note says "Log a new transfer without a commitment or plan". When I filled out the form and clicked Save, nothing happened.  Checked EconomicEvents in Django Admin, no such events.

**Comment by bhaugen** [comment]
Screenshot:
![screenshot from 2017-03-09 16 24 39](https://cloud.githubusercontent.com/assets/117439/23773600/8baf2374-04e5-11e7-8065-7dd75d2bbe55.png)

**Comment by bhaugen** [comment]
@bum2 @fosterlynn   This is a somewhat separate issue, but I'll put it here for now and raise a new issue later. Rental does not transfer an actual living space, it just transfers the rights to use a living space under the conditions granted by the rights. But I apparently needed to select some resource, so I did...because I was just testing. Didn't do the transfer anyway...

**Comment by bum2** [comment]
The bug is that a resource from another project you coordinate shows up as an option in this exchange, and that should not happen. I go to fix that one.

The transfer button can be disabled if the project does not have a resource of the scoped types, and place instead a message explaining that.

You are true about rentals, the transfer is perhaps a 'rights record' (non-material)... that needs to be configured also as another relation with a space, that shows up as a space 'rented' (not only 'owned' or 'is_contact'). 
When is in fiat currency, normally the rights object is a document of contract, transfered from agent to agent. When is in fair currency, if there's no document, we can make this 'contract' anyway and transfer that non-material 'resource'...

**Comment by bum2** [comment]
fixed the resource context issue in commit https://github.com/FreedomCoop/valuenetwork/commit/c6f112c7dc213a30d0cf2f85d20399b8fe795000, deployed in testocp...

**Comment by bhaugen** [comment]
Raised the rental issue here: https://github.com/FreedomCoop/valuenetwork/issues/230

That also brings up the question, does it make sense to require the selection of a resource, if the resource type is not inventoried? In other words, there will never be any resources to select.

**Comment by bhaugen** [comment]
See also https://github.com/FreedomCoop/valuenetwork/issues/233

**Comment by bhaugen** [comment]
I just retested, and this bug is still happening. I think it is serious, because it means a General app object is appearing in a place where an EconomicResourceType is required. The General app object does not have the same logic and methods as an EconomicResourceType.
